name: scheduled-cron-call

on:
    schedule:
        # Runs every 15 minutes (GitHub Actions uses UTC)
        - cron: "*/15 * * * *"
    # Allow manual trigger from GitHub UI
    workflow_dispatch:

jobs:
    call-cron-endpoint:
        runs-on: ubuntu-latest
        steps:
            - name: Call Vercel cron endpoint and validate
              run: |
                  set -euo pipefail
                  RESPONSE=$(curl -sS -X GET \
                    -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
                    https://goaldiary.vercel.app/api/cron)
                  echo "$RESPONSE" | jq '.' || true
                  # Validate strictly with jq
                  echo "$RESPONSE" | jq -e '.ok == true' >/dev/null
                  echo "Cron call succeeded"
